const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.LOS,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.JavaScriptInEvents.EventJogo_Event68_Act3,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sólido: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite48: 0},
	{Sprite50: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite61: 0},
	{Sprite59: 0},
	{Sprite68: 0},
	{espinho: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite51: 0},
	{Sprite43: 0},
	{Sprite47: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite60: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite73: 0},
	{Sprite83: 0},
	{Sprite84: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite99: 0},
	{Sprite100: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Sprite104: 0},
	{Sprite105: 0},
	{Sprite106: 0},
	{Sprite52: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite110: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{Sprite113: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Sprite116: 0},
	{Sprite117: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite121: 0},
	{Sprite123: 0},
	{Sprite124: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{Sprite134: 0},
	{invune: 0},
	{Platform: 0},
	{LineOfSight: 0},
	{Solid: 0},
	{Timer: 0},
	{Boss: 0},
	{invuneravel: 0},
	{teclaQLiberada: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{traum: 0},
	{Sprite136: 0},
	{Teclado: 0},
	{direcao: 0},
	{Flash: 0},
	{lanceiro: 0},
	{sensorlanceiro_direita: 0},
	{sensorlanceiro_esquerda: 0},
	{Anchor: 0},
	{vidahud: 0},
	{tituloTelaInicio: 0},
	{Mouse: 0},
	{Sprite139: 0},
	{Sprite140: 0},
	{Sprite49: 0},
	{Audio: 0},
	{cerca: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite122: 0},
	{Botão: 0},
	{ArrastarSoltar: 0},
	{play: 0},
	{Sprite127: 0},
	{Sprite128: 0},
	{Sprite129: 0},
	{Sprite130: 0},
	{Sprite131: 0},
	{Sprite132: 0},
	{Sprite133: 0},
	{Sprite135: 0},
	{Sprite137: 0},
	{Sprite138: 0},
	{Sprite141: 0},
	{Sprite142: 0},
	{Sprite143: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{Sprite146: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{Sprite151: 0},
	{Sprite152: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{Sprite155: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{machado: 0},
	{Âncora: 0},
	{Q: 0},
	{caixadedialogomachado: 0},
	{Piscar: 0},
	{vida: 0},
	{areadialogo: 0},
	{cabeça: 0},
	{seta: 0},
	{textojogo: 0},
	{Sprite158: 0},
	{FonteDeSprites: 0},
	{textojogo2: 0},
	{textojogo3: 0},
	{bossfalas: 0},
	{teste: 0},
	{textoboss1: 0},
	{Sprite159: 0},
	{Sprite160: 0},
	{textoboss2: 0},
	{textoboss3: 0},
	{textoboss4: 0},
	{trava: 0},
	{Sprite161: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{Sprite164: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{vitoria: 0},
	{libera: 0},
	{cercablo: 0},
	{cercatexto: 0},
	{Traumhud: 0},
	{barreiraboss: 0},
	{pararAudio: 0},
	{Vida: 0},
	{vidaboss: 0},
	{Bloqueioq: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	traum: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	lanceiro: class extends self.ISpriteInstance {},
	sensorlanceiro_direita: class extends self.ISpriteInstance {},
	sensorlanceiro_esquerda: class extends self.ISpriteInstance {},
	vidahud: class extends self.ISpriteInstance {},
	tituloTelaInicio: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	cerca: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	machado: class extends self.ISpriteInstance {},
	Q: class extends self.ISpriteInstance {},
	caixadedialogomachado: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	areadialogo: class extends self.ISpriteInstance {},
	cabeça: class extends self.ISpriteInstance {},
	seta: class extends self.ISpriteInstance {},
	textojogo: class extends self.ISpriteFontInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	textojogo2: class extends self.ISpriteFontInstance {},
	textojogo3: class extends self.ISpriteFontInstance {},
	bossfalas: class extends self.ISpriteInstance {},
	teste: class extends self.ISpriteInstance {},
	textoboss1: class extends self.ISpriteFontInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	textoboss2: class extends self.ISpriteFontInstance {},
	textoboss3: class extends self.ISpriteFontInstance {},
	textoboss4: class extends self.ISpriteFontInstance {},
	trava: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	vitoria: class extends self.ISpriteInstance {},
	libera: class extends self.ISpriteInstance {},
	cercablo: class extends self.ISpriteInstance {},
	cercatexto: class extends self.ISpriteFontInstance {},
	Traumhud: class extends self.ISpriteInstance {},
	barreiraboss: class extends self.ISpriteInstance {},
	pararAudio: class extends self.ISpriteInstance {}
}